# Generated by Django 4.2.11 on 2024-03-19 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_requirement",
            field=models.TextField(default="", max_length=1024, verbose_name="职位职责"),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="创建日期"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="modified_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="修改日期"
            ),
        ),
    ]
