# Generated by Django 4.2.11 on 2024-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_job_requirement_alter_job_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_requirement",
            field=models.TextField(default="", max_length=1024, verbose_name="职位需求"),
        ),
    ]
